import { Inter } from "next/font/google";
import "./globals.css";
import AudioProvider from "./_providers/AudioProvider.js"; // Adjust the path as necessary

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AudioProvider>
          {children}
        </AudioProvider>
      </body>
    </html>
  );
}
